DAT0 DATA '003003                 OCTAL
DAT1 DATA +'003003                OCTAL
DAT2 DATA -'003003                OCTAL
DAT3 DATA H5A                     HEX
DAT4 DATA +H5A                    HEX
DAT5 DATA -H5A                    HEX
DAT6 DATA 30                      DECIMAL
DAT7 DATA *                       CURRENT ADDRESS
DAT8 DATA 23.456B10               FIXED POINT SINGLE PRECISION
DAT9 DATA 103.637942C10           FIXED POINT DOUBLE PRECISION
DATA DATA 22.3344E0               FLOATING POINT, WITH PSEUDO OP LABEL
DATB DATA .12345D2                FLOATING POINT DOUBLE PRECISION
DATC DATA ''HELP''                STRING
DATD DATA ''HELLOWORLD!''         ODD LENGTH STRING
DATE DATA 1,2,3,4,5,6             LIST OF DATA
DATF DATA 1                       COMMENTED DATA
DATG DATA 1,2,3,4,5,6             COMMENTED LIST
DATH DATA DAT0+DAT1+1             SYMBOLIC
DATI DATA DAT0,DAT1+1,DAT4        SYMBOLIC LIST

     END
